# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      blog_title: 
        description: "Title of the blog being published"
        required: true
      file_path: 
        description: "The path to the blog file from the project root"
        required: true
      branch:
        description: "Git repo branch"
        default: "publish"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: jurimullercloud/md2medium-publisher:v1.2
      env:
        NTEGRATION_TOKEN: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
        REPO_ADDRESS: 'jurimullercloud/blogs'
        BRANCH: ${{ github.event.inputs.branch }}
        FILE_PATH: ${{ github.event.inputs.file_path }}'
        BLOG_TITLE: ${{ github.event.inputs.blog_title }}'
    steps:
      - name: Verify
        run: echo "Done!" 